version: '3'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_URL: [DB_URL}
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: [USER]
      N8N_BASIC_AUTH_PASSWORD: [PASSWORD]
      N8N_HOST: "0.0.0.0"
      N8N_PORT: "5678"
      WEBHOOK_TUNNEL_URL: "https://sinqura-n8n.onrender.com/"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
